### ISSUE TITLE
Ajax in option page

### ISSUE THREAD

**Issue by kammaii** [kammaii/akorean#11]
When I click 'Report bugs' and 'Get the new app news by e-mail' link in the option page, it loads google questionnaire page on the whole page.
But I want to load it on the class of 'page__content'. 
So I added javascript code like below.
```
    function report() {
      $(".page__content").load("https://goo.gl/forms/AjCBq8c2CXduqiug1");
    }

    function email() {
      $(".page__content").load("https://goo.gl/forms/B1q3m4ygXVSvMgY72");
    }
```
After I pull it to server, I clicked that anchor tag. 
But there is an error like below.
```
Access to XMLHttpRequest at 'https://goo.gl/forms/B1q3m4ygXVSvMgY72' from origin 'http://13.251.89.227' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
How to solve this problem?

**Comment by upgradingdave** [comment]
Hi Danny, like we discussed, this is because of the "same origin policy" in browsers. The same origin policy only allows files to be loaded from the same domain.   https://www.w3.org/Security/wiki/Same_Origin_Policy

If you click the "sharing" option for the google form, you can use the "iframe" code that google provides.
