### ISSUE TITLE
I experienced something awesome but I don't know why exactly.

### ISSUE THREAD

**Issue by kammaii** [kammaii/akorean#3]
I experienced something awesome but I don't know why exactly.
Yesterday I was struggling to make 'Changing consonant with anchor button' and failed. (r1/std_con.html)
I thought it is really easy to make but I couldn't understand why it is failed.
So I set break point to solve this problem. And I realized that something wrong.
When I click(actually 'touch') the right or left anchor button(line20 & 22), each function (leftHangul and rightHangul) will be run. And it changed consonant to next one. (It works well so far.)
But I found that line42 run again after changing consonant. It reset 'countClick' to 0 again! And the consonant was also reset to 'ㄱ'.
I couldn't understand why the line 42 is run again. **<-- This is my first question.**

Because we have no lesson for holiday, I gave up and tried to make 'Swipe with pure Javascript' function. And I searched good example and adapted it to my code. (from line 58 to 109)
Swipe function works well and suddenly the 'anchor button' also works well!
I set break point again to figure out this situation.
And I think the 'Swipe' function realize the 'click anchor button' to 'touchstart' and it jump over line42.
Am I correct? **<-- This is my second question.**

**Comment by upgradingdave** [comment]
Hi Danny! Very cool stuff!

1. I think the `swipedetect` and `handleswipe` functions were confusing, so I removed them in order to simplify things. I will check in the code with some notes, please take a look. 

2. Please see my comments in the code. I hope it helps you to understand how the code is working. I you have questions, just let me know!
